#!/bin/bash

file="$1"
line="$2"
debug="$3"

echo file: $file
echo line: $line
echo debug: $debug

if [[ -n "$debug" ]]; then
    # Echo all the commands
    set -x
fi

for server in `mvim --serverlist`
do
    finished=`mvim --servername $server --remote-expr "MVS_Focus('$file', '$line')"`
    if [[ $finished > 0 ]]
    then
      echo Succeeded on servername: $server
      break
    fi
done
