#!/bin/bash

file="`basename $1`"
line="$2"
mvim="$3"
debug="$4"

echo file: $file
echo line: $line
echo debug: $debug
echo `date` $0 $file $line $debug >> ~/macvim-load-line.log
echo $mvim: `which $mvim` >> ~/macvim-load-line.log

for server in `$mvim --serverlist` 
do
    if [[ $debug ]] ; then
        echo $mvim --servername $server --remote-expr "WhichTab('$file')";
        echo $mvim --servername $server --remote-expr "WhichTab('$file')"; >> ~/macvim-load-line.log
    fi
    foundfile=`$mvim --servername $server --remote-expr "WhichTab('$file')"`
    if [[ $foundfile > 0 ]]
    then
        $mvim --servername $server --remote-expr "foreground()" 
        if [[ $debug ]] ; then echo $mvim --servername $server --remote-send ":exec \"tabnext $foundfile\" <CR>"; fi
        $mvim --servername $server --remote-send ":exec \"tabnext $foundfile\" <CR>"
        if [[ $debug ]] ; then echo $mvim --servername $server --remote-send ":$line <CR>"; fi
        $mvim --servername $server --remote-send ":$line <CR>"
    fi
done
